### ISSUE TITLE
Updater doesn't work

### ISSUE THREAD

**Issue by wads24** [BoardTools/upload#48]
When I clicked "update" to update Upload Extensions..... I go the below error.

"The extension wasn’t uploaded. Please confirm that you upload the true extension zip file and try again."

Screenshot: http://pichost.org/images/2019/01/04/Capture.jpg

**Comment by lavigor** [comment]
Hi, @wads24 
I'm sorry for not being able to provide an instant fix, the issue is now resolved.
Thank you for reporting.

**Comment by wads24** [comment]
I downloaded most recent version and still showing styling issue...
